# Stage 1: Build
FROM node:20-alpine AS builder
WORKDIR /usr/src/app

# Copy package files & install dependencies
COPY package*.json ./
RUN npm install

# Copy source code & build
COPY . .
RUN npm run build

# Stage 2: Production image
FROM node:20-alpine
WORKDIR /usr/src/app

# Copy only production files
COPY --from=builder /usr/src/app/package*.json ./
COPY --from=builder /usr/src/app/dist ./dist
RUN npm install --production

# Cloud Run will inject PORT
EXPOSE 4000
CMD ["node", "dist/main.js"]